Repository Bapull/project_CodingSupporter-nestjs-deployment-repo, pull requests merged in 2024-11, with the labels that each got.

#46 CI/CD 파일 사이즈 최적화 작업
  .dockerignore
  Dockerfile
Labels: 🛠️ Refactor, ⭐ Feature, 🚀 Deploy

#47 💫 edit: Modify the docker file
  Dockerfile
Labels: 🐛 BugFix, 💡 Enhancement, 🚀 Deploy

#50 Docker file 수정
  Dockerfile
Labels: 🐛 BugFix, 🛠️ Refactor, 🚀 Deploy

#51 Refactor/docker deploy
  .github/workflows/cd.yml
  Dockerfile
Labels: 🐛 BugFix, 🛠️ Refactor, 🚀 Deploy

#52 CD 파일의 SSL 환경변수 공백 처리 수정
  .github/workflows/ci.yml
Labels: 🛠️ Refactor, 🚀 Deploy

#53 cd yml 파일 공백 제거
  .github/workflows/cd.yml
Labels: 🐛 BugFix, 🛠️ Refactor, 🚀 Deploy

#55 Docker 배포 명령어 수정
  .github/workflows/cd.yml
Labels: 🐛 BugFix, 🛠️ Refactor, 🚀 Deploy

#56 CD 명령어 수정
  .github/workflows/cd.yml
Labels: 🛠️ Refactor, 🚀 Deploy

#58 OpenAI API 키 환경변수 추가
  .github/workflows/cd.yml
Labels: ⭐ Feature, 🚀 Deploy

#59 OpenAI API Key 변수명 수정
  .github/workflows/cd.yml
Labels: 🛠️ Refactor, 🚀 Deploy

#61 Feature/chatting 에러타입 엔드포인트 추가
  src/incorrect-note/incorrect-note.service.ts
  src/user/user.controller.ts
  src/utils/types.ts
Labels: ⭐ Feature

#70 채팅 저장기능, 세션 레디스 저장 기능, 채팅시 권한확인 기능도 추가
  .env.example
  .gitignore
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/utils/GoogleStrategy.ts
  src/chat-room/chat-room.controller.spec.ts
  src/chat-room/chat-room.controller.ts
  src/chat-room/chat-room.module.ts
  src/chat-room/chat-room.service.spec.ts
  src/chat-room/chat-room.service.ts
  src/chat-room/dto/create-chat-room.dto.ts
  src/chat-room/entities/chat-room.entity.ts
  src/chat/chat.gateway.ts
  src/chat/chat.guard.spec.ts
  src/chat/chat.guard.ts
  src/chat/chat.module.ts
  src/httpsOptions.ts
  src/main.ts
  src/message/dto/create-message.dto.ts
  src/message/dto/update-message.dto.ts
  src/message/message.controller.spec.ts
  src/message/message.controller.ts
  src/message/message.guard.ts
  src/message/message.module.ts
  src/message/message.service.spec.ts
  src/message/message.service.ts
  src/message/schemas/message.schema.ts
  src/notification/dto/update-notification.dto.ts
  src/notification/notification.controller.spec.ts
  src/notification/notification.controller.ts
  src/notification/notification.module.ts
  src/notification/notification.service.ts
  src/setting/cors.ts
  src/setting/httpsOptions.ts
  src/setting/init.sesstion.ts
  src/user/user.controller.ts
  src/utils/types.ts
Labels: 🐛 BugFix, 🛠️ Refactor, ⭐ Feature

#75 더 나은 멘토 로딩 방식
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/common/types.ts
  src/setting/init.sesstion.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: ⭐ Feature

#76 Refactoring/issue number#68
  package-lock.json
  package.json
  src/app.module.ts
  src/attendance/attendance.module.ts
  src/attendance/attendance.service.ts
  src/auth/auth.controller.ts
  src/chat-room/chat-room.controller.ts
  src/chat-room/chat-room.module.ts
  src/chat-room/chat-room.service.ts
  src/incorrect-note/incorrect-note.controller.ts
  src/incorrect-note/incorrect-note.module.ts
  src/incorrect-note/incorrect-note.service.ts
  src/lang-chain/lang-chain.service.ts
  src/message/dto/create-message.dto.ts
  src/message/entities/message.entity.ts
  src/message/message.controller.ts
  src/message/message.module.ts
  src/message/message.service.ts
  src/message/schemas/message.schema.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
Labels: 🛠️ Refactor

#79 이메일 전송을 위한 엔드포인트 추가
  .env.example
  package-lock.json
  package.json
  src/app.module.ts
  src/common/types.ts
  src/email/dto/email.dto.ts
  src/email/email.controller.spec.ts
  src/email/email.controller.ts
  src/email/email.module.ts
  src/email/email.service.spec.ts
  src/email/email.service.ts
Labels: ⭐ Feature

#81 오답노트 중복저장 문제 해결, 오답노트 저장할 때 저장된 노트의 아이디도 반환
  src/incorrect-note/dto/save-incorrect-note.dto.ts
  src/incorrect-note/entities/incorrect-note.entity.ts
  src/incorrect-note/incorrect-note.controller.ts
  src/incorrect-note/incorrect-note.service.ts
  src/s3/s3.service.ts
Labels: 🐛 BugFix, 💡 Enhancement
