Repository Bapull/project_CodingSupporter-nestjs-deployment-repo, pull requests merged in 2024-10, with the labels that each got.

#4 Feature/deployment
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/main.yml
  Dockerfile
Labels: ⭐ Feature, 🚀 Deploy

#5 💫 Edit: Fix GitHub Actions ci.yml
  .github/workflows/ci.yml
Labels: 🐛 BugFix, 🚀 Deploy

#7 💫 Fix: Fix GitHub Actions ci.yml
  .github/workflows/ci.yml
Labels: 🐛 BugFix, 🚀 Deploy

#10 Feature/user info
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Dockerfile
  src/app.module.ts
  src/attendance/attendance.controller.spec.ts
  src/attendance/attendance.controller.ts
  src/attendance/attendance.module.ts
  src/attendance/attendance.service.spec.ts
  src/attendance/attendance.service.ts
  src/attendance/dto/create-attendance.dto.ts
  src/attendance/dto/update-attendance.dto.ts
  src/attendance/entities/attendance.entity.ts
  src/auth/utils/Serializer.ts
  src/incorrect-note/incorrect-note.controller.ts
  src/incorrect-note/incorrect-note.module.ts
  src/incorrect-note/incorrect-note.service.ts
  src/user/user.controller.ts
  src/user/user.module.ts
Labels: 💻 API, ⭐ Feature

#13 🔨 Refactored: update git actions Deploy to EC2 cd.yml file deployment…
  .github/workflows/cd.yml
Labels: 🐛 BugFix, 🚀 Deploy

#15 🔨refactor: Change HTTPS option
  src/main.ts
Labels: 🛠️ Refactor, 🚀 Deploy

#18 Refactor/sql#14
  .env.example
Labels: 🛠️ Refactor

#19 App Module SQL 접근 권한 변경
  src/app.module.ts
Labels: 🛠️ Refactor, 🚀 Deploy

#20 Add a Docker Compose File
  docker-compose.yml
Labels: ⭐ Feature

#21 [TypeOrmModule] 데이터베이스에 문제 해결
  src/app.module.ts
Labels: 🛠️ Refactor, 🚀 Deploy

#22 Feature/lang chain
  package-lock.json
  package.json
  src/app.controller.ts
  src/app.module.ts
  src/incorrect-note/dto/generate-incorrect-note.dto.ts
  src/incorrect-note/incorrect-note.controller.ts
  src/lang-chain/lang-chain.controller.spec.ts
  src/lang-chain/lang-chain.controller.ts
  src/lang-chain/lang-chain.module.ts
  src/lang-chain/lang-chain.service.spec.ts
  src/lang-chain/lang-chain.service.ts
  src/lang-chain/langChain.ts
  src/main.ts
Labels: ⭐ Feature

#25 CD Yml 파일 수정
  .github/workflows/cd.yml
Labels: 🐛 BugFix, 🛠️ Refactor, 🚀 Deploy

#27 Google OAuth2 권한 추가
  .github/workflows/cd.yml
Labels: ⭐ Feature, 🚀 Deploy

#30 Edit/llm llm 동작방식 변경
  package-lock.json
  package.json
  src/app.service.ts
  src/auth/utils/GoogleStrategy.ts
  src/incorrect-note/dto/generate-incorrect-note.dto.ts
  src/incorrect-note/incorrect-note.controller.ts
  src/incorrect-note/incorrect-note.module.ts
  src/incorrect-note/incorrect-note.service.ts
  src/lang-chain/lang-chain.controller.spec.ts
  src/lang-chain/lang-chain.controller.ts
  src/lang-chain/lang-chain.module.ts
  src/lang-chain/lang-chain.service.ts
  src/lang-chain/langChain.ts
  src/main.ts
  src/user/user.controller.ts
  src/user/user.service.ts
  src/utils/swagger.ts
Labels: 🛠️ Refactor, ⭐ Feature

#34 💡 feat: Add /incorrect-note/save endpoint with S3 bucket support
  .env.example
  package-lock.json
  package.json
  src/app.module.ts
  src/incorrect-note/dto/save-incorrect-note.dto.ts
  src/incorrect-note/entities/incorrect-note.entity.ts
  src/incorrect-note/incorrect-note.controller.ts
  src/incorrect-note/incorrect-note.module.ts
  src/incorrect-note/incorrect-note.service.ts
  src/s3-service/s3-service.module.ts
  src/s3-service/s3-service.service.spec.ts
  src/s3-service/s3-service.service.ts
  src/user/entities/user.entity.ts
Labels: 🐛 BugFix, 💻 API, ⭐ Feature

#36 💡 feat: Create endpoint for downloading MD files from S3
  src/incorrect-note/incorrect-note.controller.ts
  src/incorrect-note/incorrect-note.service.ts
  src/s3-service/s3-service.service.ts
Labels: ⭐ Feature

#37 🔨refactor: Replace constants with enums in swagger annotations
  src/incorrect-note/incorrect-note.controller.ts
  src/user/user.controller.ts
  src/utils/swagger.ts
Labels: 🛠️ Refactor

#40 🔨refactor: Store only user ID in session instead of user object
  src/auth/auth.service.ts
  src/auth/utils/Guards.ts
  src/auth/utils/Serializer.ts
  src/user/user.service.ts
Labels: 🛠️ Refactor

#42 💫fix: Restrict attendance check to once per day
  src/attendance/dto/create-attendance.dto.ts
  src/attendance/entities/attendance.entity.ts
  src/user/user.controller.ts
Labels: 🐛 BugFix, 💡 Enhancement

#44 코드 리팩토링
  src/auth/auth.guard.spec.ts
  src/auth/auth.guard.ts
  src/auth/utils/GoogleStrategy.ts
  src/httpsOptions.ts
  src/incorrect-note/dto/create-incorrect-note.dto.ts
  src/incorrect-note/dto/generate-incorrect-note.dto.ts
  src/incorrect-note/dto/get-s3-file.dto.ts
  src/incorrect-note/dto/language-and-errortype.dto.ts
  src/incorrect-note/dto/save-incorrect-note.dto.ts
  src/incorrect-note/incorrect-note.controller.ts
  src/main.ts
  src/user/user.controller.ts
Labels: 🛠️ Refactor
